project:
  type: website
  output-dir: docs

website:
  title: "The Amariuta Lab"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: github.qmd
        text: Github
      - href: genomebrowser.qmd
        text: IMPACT on the UCSC Genome Browser
      - href: people.qmd
        text: Lab Members
    background: dark
  page-footer:
    left: |
      **Contact Information**<br>
      tamariutabartell [*at*] ucsd [*dot*] edu<br>
      Franklin Antonio Hall, Voigt Drive, La Jolla, CA 92093
    right: |
      Halıcıoğlu Data Science Institute<br>
      Department of Medicine<br>
      University of California, San Diego<br>
    background: dark

format:
  html:
    theme:
      - brand
    css: styles.css
    toc: false
    page-layout: full
